### ISSUE TITLE
Error handling when switching to non-existing locale

### ISSUE THREAD

**Issue by jzaefferer** [jquery/globalize#302]
This throws up a random error when the locale isn't available:

```js
Globalize.locale("ar")
```

It should probably complain about the lack of the "ar" Cldr data.

Happens on doc/hello-world/plain-javascript/

**Comment by jzaefferer** [comment]
This might have been resolved by the recent bundle lookup changes. Could you verify?

**Comment by rxaviers** [comment]
This hasn't changed.

If user doesn't load likelySubtags data, the validation works just fine:
```
> var cldrData = require( "cldr-data" );
undefined
> var Globalize = require( "globalize" );
undefined
> Globalize.locale("en")
Error: E_MISSING_CLDR: Missing required CLDR content `supplemental/likelySubtags`.
    at createError (/tmp/node_modules/globalize/dist/globalize.js:105:10)
    at validate (/tmp/node_modules/globalize/dist/globalize.js:118:9)
    at EventEmitter.validateCldr (/tmp/node_modules/globalize/dist/globalize.js:140:2)
    at EventEmitter.emitEvent (/tmp/node_modules/cldrjs/dist/cldr/event.js:416:35)
    at EventEmitter.aliasClosure [as trigger] (/tmp/node_modules/cldrjs/dist/cldr/event.js:88:22)
    at Cldr.get (/tmp/node_modules/cldrjs/dist/cldr/event.js:572:12)
    at validateLikelySubtags (/tmp/node_modules/globalize/dist/globalize.js:273:7)
    at Function.Globalize.locale (/tmp/node_modules/globalize/dist/globalize.js:327:3)
    at repl:1:12
    at REPLServer.self.eval (repl.js:110:21)
```

Although, if for some reason, user loads an incomplete likelySubtags dataset, it bypasses the validations and some other error is thrown.

```
> Globalize.load({supplemental: {likelySubtags: {}}})
undefined
> Globalize.locale("en")
TypeError: Cannot call method 'split' of undefined
    at coreLikelySubtags (/tmp/node_modules/cldrjs/dist/cldr.js:161:56)
    at Cldr.init (/tmp/node_modules/cldrjs/dist/cldr.js:596:19)
    at Cldr.init (/tmp/node_modules/cldrjs/dist/cldr/event.js:554:13)
    at Cldr.init (/tmp/node_modules/cldrjs/dist/cldr/supplemental.js:92:13)
    at new Cldr (/tmp/node_modules/cldrjs/dist/cldr.js:538:8)
    at alwaysCldr (/tmp/node_modules/globalize/dist/globalize.js:243:55)
    at Function.Globalize.locale (/tmp/node_modules/globalize/dist/globalize.js:326:15)
    at repl:1:12
    at REPLServer.self.eval (repl.js:110:21)
    at Interface.<anonymous> (repl.js:239:12)
```

If user loads likelySubtags, it works just fine.
```
Globalize.load(cldrData("supplemental/likelySubtags"))
Globalize.locale("en"); // works just fine
```

Validation for partially loaded data could be implemented if it turns out to be a recurring problem. I would focus on other issues for now.

**Comment by jzaefferer** [comment]
Okay, let's leave this open for a while (easier to find). If no one else runs into this after 1.0 is released, we can eventually just ignore it an close this issue.

**Comment by rxaviers** [comment]
Closing this issue because no one has ever ran into it. Loading partial data seems odd enough.
