### ISSUE TITLE
Message inheritance is broken

### ISSUE THREAD

**Issue by devangnegandhi** [jquery/globalize#408]
Hi, after I upgraded globalize to 1.0.0-alpha.16, the inheritance feature as fixed in #266 and mentioned in https://github.com/jquery/globalize/blob/master/doc/api/message/load-messages.md#messages-inheritance seems to be broken. I get the following error if I try to call formatMessage() method on a locale for which no message was loaded

```
Error: E_MISSING_MESSAGE_BUNDLE: Missing message bundle for locale `de`.
    at createError (/home/devang/tmp/Globalize/node_modules/globalize/dist/globalize.js:105:10)
    at validate (/home/devang/tmp/Globalize/node_modules/globalize/dist/globalize.js:118:9)
    at validateMessageBundle (/home/devang/tmp/Globalize/node_modules/globalize/dist/globalize/message.js:1705:2)
    at Globalize.messageFormatter.Globalize.messageFormatter (/home/devang/tmp/Globalize/node_modules/globalize/dist/globalize/message.js:1822:2)
    at Globalize.formatMessage.Globalize.formatMessage (/home/devang/tmp/Globalize/node_modules/globalize/dist/globalize/message.js:1855:14)
    at Object.<anonymous> (/home/devang/tmp/Globalize/i18n.js:19:31)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

This is working fine in version 1.0.0-alpha.15

**Comment by rxaviers** [comment]
Thanks for filing this issue. I have updated the documentation accordingly.

Short answer: you should let Globalize know `de` is a valid bundle. In case all its messages are going to be inherited, define it by using an empty set.

```
Globalize.loadMessages({
  de: {}
});
```

Long answer: Although the bundle inheritance chain is predefined independent of any loaded data (e.g., `en-IN` chain is: `en-IN` ➡ `en-GB` (via parent locale) ➡ `en-001` (via parent locale) ➡ `en` (via truncation)  ➡ `root`), the bundle lookup depends on the available loaded bundles (e.g., the bundle for `zh-TW` could be either `zh-Hant` or `zh-Hant-TW` depending on the available bundles). See also https://github.com/rxaviers/cldrjs/blob/master/doc/bundle_lookup_matcher.md#implementation-details.

Please, just let me know if having to load the empty set in that case turns out to be a problem.
