### ISSUE TITLE
app-npm-webpack example is not working in dev server mode

### ISSUE THREAD

**Issue by aliry** [jquery/globalize#624]
I was trying to follow the readme file to run webpack dev server for the app-npm-webpack example.

"npm start" script throws with the following exception:
 70% 1/1 build modulesevents.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EACCES
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1129:19)
    at listen (net.js:1172:10)
    at net.js:1270:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:81:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:99:10)

FYI: production build ("npm run build") works fine

**Comment by jzaefferer** [comment]
Do you have another app/server running on the same port?

**Comment by aliry** [comment]
I didn't. But I've changed the port and worked.

Thanks for the hint.
